# Generated by Django 3.2 on 2021-04-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lasname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=13)),
                ('emile', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
