# Generated by Django 3.2 on 2021-04-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_auto_20210412_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxis',
            name='phone',
        ),
    ]
