# Generated by Django 3.2 on 2021-04-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_remove_taxis_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxis',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
