# Generated by Django 3.2 on 2021-04-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_alter_taxis_emile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxis',
            old_name='emile',
            new_name='email',
        ),
    ]
