# Generated by Django 3.2 on 2021-04-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0006_rename_emile_taxis_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxis',
            name='color',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxis',
            name='license',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
