# Generated by Django 3.2 on 2021-04-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_auto_20210412_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
