# Generated by Django 3.2 on 2021-04-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0009_auto_20210414_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='nomber'),
        ),
    ]
