# Generated by Django 3.1.7 on 2021-04-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0010_alter_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taxis',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
